name: 'Build'

on:
  push:
  pull_request:

jobs:
  terraform:
    env:
      AWS_DEFAULT_REGION: us-east-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Use example users_groups to test
        run: mv _var_users_groups.example.json _var_users_groups.auto.tfvars.json

      - name: Validate Terraform config
        run: terraform validate

      - name: Terraform security scan
        uses: triat/terraform-security-scan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform plan
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform plan -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
